title: Herhaal lus
hero_image: images/banner.png
description: Hoe je iets een vast aantal keren kunt herhalen
version: 4
listed: false
copyedit: false
last_tested: "2023-09-26"
steps:
  - 
    title: Inleiding
