title: micro:bit repeat
hero_image: images/banner.png
description: How to repeat something a fixed number of times 
version: 4
listed: false
copyedit: false
last_tested: "2023-09-26"
steps:
  - title: Introduction