---
title: Boucle répéter
hero_image: images/banner.png
description: Comment répéter quelque chose un nombre fixe de fois
version: 4
listed: false
copyedit: false
last_tested: "2023-09-26"
steps:
  - title: Introduction
